### ISSUE TITLE
problem with "import hydrobr"

### ISSUE THREAD

**Issue by leormonteiro** [wallissoncarvalho/hydrobr#7]
Oi eu estou tentando utilizar o programa, entretanto estou esbarrando em um problema. Quando uso o comando "import hydrobr" ele dá a seguinte mensagem de erro:

import-im6.q16: unable to open image `hydrobr': Is a directory @ error/blob.c/OpenBlob/2874.
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.

Eu estou utilizando um uUuntu 20.04. Você sabe me dizer qual é o problema?

Atenciosamente

**Comment by wallissoncarvalho** [comment]
Olá, 
Pela mensagem de erro parece que você não está executando o comando com o python3.

Instalei o ubunto 20.04 e executei os seguintes comandos em ordem:
$ sudo apt install python3-pip
$ pip3 install hydrobr
$ python3   - Para ativar o python
$ import hydrobr
--
Não recebi nenhuma mensagem de erro.
Verifica se você realmente executou o compando `import hydrobr` em um terminal com o python3 ativo.

--
Caso esta resposta resolva seu problema feche a issue por favor.

**Comment by leormonteiro** [comment]
Obrigado Wallisson,

Realmente era o python. Eu estava usando o 2.7.
